service: leighton-cqrs-control
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: eu-west-2
  versionFunctions: false 

plugins:
  - serverless-plugin-typescript

functions:
  processStream:
    handler: src/processStream.handler
    role: processStreamRole
    environment:
      EVENT_BUS_NAME: ${self:custom.eventBusName}
      TABLE_NAME: ${self:custom.ledger.tableName}
      STAGE_NAME: ${opt:stage}
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.ledger.streamARN}

params:
  production:
    logLevel: WARN

  uat:
    logLevel: INFO

  staging:
    logLevel: DEBUG

  dev:
    logLevel: DEBUG


custom:
  ledger:
    arn: !GetAtt ledgerTable.Arn
    tableName: ${self:service}-${opt:stage}-ledgerTable
    streamARN: !GetAtt ledgerTable.StreamArn
  eventBusName: ${self:service}-application-bus-${self:provider.stage}
  eventBusARN: !GetAtt EventBridgeBus.Arn
resources:
  - ${file(./resources/dynamoTables.yml)}
  - ${file(./resources/eventBus.yml)}
  - ${file(./roles/processStreamRole.yml)}

  
